### ISSUE TITLE
RSVPs using the Sustaining Partners RSVP Form aren't populating in Event page's RSVP list

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#119]
Hi @JasonTheAdams  
I originally emailed this to you but I did some digging into this and have new information so am now going thru the official SOP to make this github issue :)

ORIGINAL EMAIL sent Feb 27, 2024, 1:03 PM -- 
Oh boy. So I did a thing that I thought would be easy but it's not.

I duplicated the Orientation form to use it for our new Sustaining Partners events. So I have this nice, new Sustaining Partners RSVP Form we can use with specific entry fields.

HOWEVER, the RSVPs that are coming in, are not being recognized in the RSVP list on the event page!

1. Still showing we need 30 when we have 3 RSVPs
https://sdrefugeetutoring.com/event/march2024-sustaining-partners-circle/

2. Still showing we need 30 when we have 2 RSVPs
https://sdrefugeetutoring.com/event/may2024-sustaining-partners-circle/

****EDIT--** In looking at the actual RSVPs, they do not have a date or title attached to them like the other RSVPs!
Screenshot:** 

![Screenshot (64)](https://github.com/SDRefugeeTutoring/sdrt-custom-functions/assets/47679296/f7f5c8c2-ab56-48bc-80bd-68250cd2a1ac)

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

So this had the exact same underlying problem as #118 — the issue with RSVPs doing the same thing. I implemented the same fix. I also noticed the "Sustaining Partner RSVP" form was also generating an RSVP, so I updated that form as well.

Let me know if you see any further issues with this!

**Comment by dreazee** [comment]
@JasonTheAdams oh yay!!! So glad it was an easy fix. Thank you!! :)

**Comment by dreazee** [comment]
Hi @JasonTheAdams This fix doesn't look to have taken... Still having this issue!

We received a new May RSVP after the fix and I noticed it didn't populate in the RSVP list on the event page.
Then I just tested out the March event by submitting a test RSVP and it didn't populate. I made sure I was logged in correctly to WP, too!
